version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      # Framework gems
      - dependency-name: activesupport
        dependency-type: direct
      - dependency-name: middleman
        dependency-type: direct
      - dependency-name: redcarpet
        dependency-type: direct
