name: Build and push images

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: Decide on build type
        required: true
        type: choice
        options:
          - build_push
          - build_only
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: datagovuk-tech-docs
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef }}
      - name: Build images (without pushing to registry)
        if: ${{ inputs.buildType == 'build_only' }}
        env:
          DRY_RUN: "1"
          APP: datagovuk-tech-docs
          ARCH: amd64
        run: ./docker/build-image.sh
      - name: Build and push images
        if: ${{ inputs.buildType == 'build_push' || github.ref == 'refs/heads/main' }}
        env:
          APP: datagovuk-tech-docs
          ARCH: amd64
        run: ./docker/build-image.sh
